defaults:
  - base
  - _self_

mode: eval_suffix_dataset

eval:
  batch_size: 8
  suffix_dataset_pth_dct:
    suffixes_eval_1: ... # path to csv, should contain columns 'instruct', 'target', 'suffix', 'full_instruct'
    suffixes_eval_2: ...
